services:
  agent_service:
    image: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-agent"
    ports:
      - "8080:8080"
    env_file:
      - .env

  streamlit_app:
    image: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-ui"
    ports:
      - "8501:8501"
    depends_on:
      - agent_service
    environment:
      - AGENT_URL=http://agent_service:8080
    volumes:
      - "./temp_mount:/app/mount"
